# Generated by Django 4.2.16 on 2024-11-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('number_offices', models.IntegerField(blank=True, default=0, verbose_name='Количество офисов')),
                ('number_atms', models.IntegerField(blank=True, default=0, verbose_name='Количество ATM')),
                ('number_employees', models.IntegerField(blank=True, default=0, verbose_name='Количество сотрудников')),
                ('number_clients', models.IntegerField(blank=True, default=0, verbose_name='Количество клиентов')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('total_money', models.IntegerField(blank=True, null=True, verbose_name='Всего денег')),
                ('interest_rate', models.FloatField(blank=True, null=True, verbose_name='Процентная ставка')),
            ],
        ),
        migrations.CreateModel(
            name='BankOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('work', 'работает'), ('not work', 'не работает')], default='work', max_length=255, verbose_name='Статус')),
                ('can_place_atm', models.BooleanField(verbose_name='Можно ли расположить автомат')),
                ('num_atms', models.IntegerField(default=0, verbose_name='Количество автоматов')),
                ('can_provide_credit', models.BooleanField(verbose_name='Может выдавать кредит')),
                ('dispense_money', models.BooleanField(verbose_name='Работает на выдачу денег')),
                ('accept_money', models.BooleanField(verbose_name='Можно ли внести деньги')),
                ('money_in_office', models.IntegerField(blank=True, default=0, null=True, verbose_name='Денег в офисе')),
                ('rent_cost', models.FloatField(verbose_name='Стоимость аренды банковского офиса')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bank', verbose_name='Банк')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('job', models.CharField(max_length=255, verbose_name='Место работы')),
                ('monthly_income', models.FloatField(verbose_name='Месячная зарплата')),
                ('credit_rating', models.IntegerField(blank=True, null=True, verbose_name='Кредитный рейтинг')),
                ('banks', models.ManyToManyField(to='banks_app.bank', verbose_name='Банки')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('balance', models.FloatField(verbose_name='Баланс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('works_remotely', models.BooleanField(verbose_name='Работает удаленно')),
                ('can_provide_credit', models.BooleanField(verbose_name='Может выдавать кредит')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bank', verbose_name='Банк')),
                ('bank_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bankoffice', verbose_name='Офис банка')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала кредита')),
                ('end_date', models.DateField(verbose_name='Дата окончания кредита')),
                ('loan_duration_months', models.IntegerField(verbose_name='Продолжительность в месяцах')),
                ('loan_amount', models.FloatField(verbose_name='Сумма кредита')),
                ('monthly_payment', models.FloatField(verbose_name='Ежемесячный платеж')),
                ('interest_rate', models.FloatField(blank=True, null=True, verbose_name='Процентная ставка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.employee', verbose_name='Сотрудник')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.paymentaccount', verbose_name='Платежный аккаунт')),
            ],
        ),
        migrations.CreateModel(
            name='BankAtm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('work', 'работает'), ('not work', 'не работает'), ('not money', 'нет денег')], default='work', max_length=50, verbose_name='Статус')),
                ('dispense_money', models.BooleanField(verbose_name='Работает на выдачу денег')),
                ('accept_money', models.BooleanField(verbose_name='Можно ли внести деньги')),
                ('money_in_atm', models.IntegerField(blank=True, default=0, null=True, verbose_name='Денег в автомате')),
                ('maintenance_cost', models.FloatField(verbose_name='Стоимость обслуживания')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bank', verbose_name='Банк')),
                ('bank_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bankoffice', verbose_name='Офис банка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
